//`frontend/src/app/admin/reports/page.tsx` (NEW FILE)**


'use client';

import { useState, useEffect } from 'react';
import axios from 'axios';
import { useAuth } from '../../../../../context/AuthContext';
import { useRouter } from 'next/navigation';
import { FileBarChart, CalendarDays, UserRound } from 'lucide-react';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../../../../components/reportRecep/table';
import { Button } from '../../../../../components/ui/Button';
import ReportViewModal from '../../../../../components/reportRecep/ReportViewModal'; // NEW Component

interface ReportHistoryItem {
  _id: string;
  reportType: 'Daily' | 'Occupancy' | 'Revenue' | 'Guest';
  reportData: any; // The actual report data
  generatedBy: {
    _id: string;
    firstName: string;
    lastName: string;
    role: string;
  };
  note?: string;
  createdAt: string;
}

// const API_URL = 'https://localhost:5000';
const API_URL = process.env.NEXT_PUBLIC_API_URL || 'https://mesertehotelinformationmanagementsystem.onrender.com';
export default function AdminReportsPage() {
  const { user, loading: authLoading } = useAuth();
  const router = useRouter();
  const [reports, setReports] = useState<ReportHistoryItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedReport, setSelectedReport] = useState<ReportHistoryItem | null>(null);

  useEffect(() => {
    if (!authLoading && (!user || user.role !== 'admin')) {
      router.push('/');
    } else if (user) {
      fetchReportsHistory();
    }
  }, [user, authLoading]);

  const fetchReportsHistory = async () => {
    setLoading(true);
    setError(null);
    try {
      const response = await axios.get<ReportHistoryItem[]>(`${API_URL}/api/reports/history`, {
        withCredentials: true,
      });
      setReports(response.data);
    } catch (err: any) {
      setError(err.response?.data?.message || 'Failed to fetch reports history.');
      console.error('Error fetching reports history:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleViewReport = (report: ReportHistoryItem) => {
    setSelectedReport(report);
    setIsModalOpen(true);
  };

  if (authLoading || (!user && !authLoading)) {
    return <div className="flex justify-center items-center min-h-screen">Loading authentication...</div>;
  }

  if (loading) {
    return <div className="p-8 text-center text-gray-600 dark:text-gray-400">Loading reports history...</div>;
  }

  if (error) {
    return <div className="p-8 text-red-600">Error: {error}</div>;
  }

  return (
    <div className="container mx-auto p-6 bg-gray-50 dark:bg-gray-900 min-h-screen">
      <h1 className="text-3xl font-bold mb-8 text-gray-900 dark:text-white flex items-center">
        <FileBarChart className="mr-3" size={32} /> Report History (Admin)
      </h1>

      {reports.length === 0 ? (
        <div className="text-center text-gray-600 dark:text-gray-400 mt-10">
          No reports have been generated yet.
        </div>
      ) : (
        <div className="bg-white dark:bg-gray-800 shadow-lg rounded-lg overflow-hidden border border-gray-200 dark:border-gray-700">
          <Table>
            <TableHeader className="bg-gray-100 dark:bg-gray-700">
              <TableRow className="dark:border-gray-600">
                <TableHead className="text-gray-700 dark:text-gray-300">Report Type</TableHead>
                <TableHead className="text-gray-700 dark:text-gray-300">Generated By</TableHead>
                <TableHead className="text-gray-700 dark:text-gray-300">Date</TableHead>
                <TableHead className="text-gray-700 dark:text-gray-300">Note</TableHead>
                <TableHead className="text-right text-gray-700 dark:text-gray-300">Actions</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {reports.map((report) => (
                <TableRow key={report._id} className="dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700/50">
                  <TableCell className="font-medium text-gray-900 dark:text-white">{report.reportType}</TableCell>
                  <TableCell className="text-gray-700 dark:text-gray-300 flex items-center">
                    <UserRound size={16} className="mr-2 text-gray-500" />
                    {report.generatedBy.firstName} {report.generatedBy.lastName} ({report.generatedBy.role})
                  </TableCell>
                  <TableCell className="text-gray-700 dark:text-gray-300 flex items-center">
                    <CalendarDays size={16} className="mr-2 text-gray-500" />
                    {new Date(report.createdAt).toLocaleString()}
                  </TableCell>
                  <TableCell className="text-gray-700 dark:text-gray-300 max-w-xs truncate">{report.note || 'N/A'}</TableCell>
                  <TableCell className="text-right">
                    <Button
                      onClick={() => handleViewReport(report)}
                      className="px-3 py-1 text-sm bg-blue-500 hover:bg-blue-600 text-white dark:bg-blue-600 dark:hover:bg-blue-700"
                    >
                      View Report
                    </Button>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      )}

      {selectedReport && (
        <ReportViewModal
          isOpen={isModalOpen}
          onClose={() => setIsModalOpen(false)}
          report={selectedReport}
        />
      )}
    </div>
  );
}
/*// src/app/admin/report/page.tsx
'use client';

import { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '../../../../context/AuthContext';
import { Card, CardHeader, CardTitle, CardDescription } from '../../../../components/reportRecep/card';
import { Button } from '../../../../components/ui/Button';
import { ArrowRight, CalendarDays, DollarSign, Users, Hotel } from 'lucide-react';

export default function AdminReportsPage() {
  const { user, loading: authLoading } = useAuth();
  const router = useRouter();

  useEffect(() => {
    if (!authLoading && (!user || (user.role !== 'admin' && user.role !== 'manager'))) {
      router.push('/');
    }
  }, [user, authLoading, router]);

  if (authLoading || (!user && !authLoading)) {
    return <div className="flex justify-center items-center min-h-screen text-gray-700 dark:text-gray-300">Loading authentication...</div>;
  }

  return (
    <div className="container mx-auto p-6 bg-gray-50 dark:bg-gray-900 min-h-screen">
      <h1 className="text-3xl font-bold mb-8 text-gray-900 dark:text-white flex items-center">
        <CalendarDays className="mr-3" size={32} /> Admin Reports
      </h1>

      <p className="mb-8 text-gray-700 dark:text-gray-300">
        As an Admin, you have access to all operational reports. Select a report type below to view detailed analytics.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <Card className="shadow-lg dark:bg-gray-800 dark:border-gray-700">
          <CardHeader>
            <CardTitle className="text-xl text-gray-900 dark:text-white flex items-center">
              <CalendarDays className="mr-2" /> Daily Report
            </CardTitle>
            <CardDescription className="text-gray-600 dark:text-gray-400">
              View daily summaries of check-ins, check-outs, bookings, and revenue.
            </CardDescription>
          </CardHeader>
          <div className="p-6 pt-0">
            <Button onClick={() => router.push('/receptionist/reports/daily')} className="w-full bg-amber-500 hover:bg-amber-600 text-white dark:bg-amber-600 dark:hover:bg-amber-700">
              View Daily Report <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </div>
        </Card>

        <Card className="shadow-lg dark:bg-gray-800 dark:border-gray-700">
          <CardHeader>
            <CardTitle className="text-xl text-gray-900 dark:text-white flex items-center">
              <Hotel className="mr-2" /> Occupancy Report
            </CardTitle>
            <CardDescription className="text-gray-600 dark:text-gray-400">
              Analyze room occupancy rates, available rooms, and total rooms over a period.
            </CardDescription>
          </CardHeader>
          <div className="p-6 pt-0">
            <Button onClick={() => router.push('/receptionist/reports/occupancy')} className="w-full bg-amber-500 hover:bg-amber-600 text-white dark:bg-amber-600 dark:hover:bg-amber-700">
              View Occupancy Report <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </div>
        </Card>

        <Card className="shadow-lg dark:bg-gray-800 dark:border-gray-700">
          <CardHeader>
            <CardTitle className="text-xl text-gray-900 dark:text-white flex items-center">
              <DollarSign className="mr-2" /> Revenue Report
            </CardTitle>
            <CardDescription className="text-gray-600 dark:text-gray-400">
              Track total revenue, food & beverage, and room booking revenue over time.
            </CardDescription>
          </CardHeader>
          <div className="p-6 pt-0">
            <Button onClick={() => router.push('/receptionist/reports/revenue')} className="w-full bg-amber-500 hover:bg-amber-600 text-white dark:bg-amber-600 dark:hover:bg-amber-700">
              View Revenue Report <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </div>
        </Card>

        <Card className="shadow-lg dark:bg-gray-800 dark:border-gray-700">
          <CardHeader>
            <CardTitle className="text-xl text-gray-900 dark:text-white flex items-center">
              <Users className="mr-2" /> Guest Report
            </CardTitle>
            <CardDescription className="text-gray-600 dark:text-gray-400">
              See statistics on new and total registered guests, including recent signups.
            </CardDescription>
          </CardHeader>
          <div className="p-6 pt-0">
            <Button onClick={() => router.push('/receptionist/reports/guests')} className="w-full bg-amber-500 hover:bg-amber-600 text-white dark:bg-amber-600 dark:hover:bg-amber-700">
              View Guest Report <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </div>
        </Card>
      </div>
    </div>
  );
}*/